-- Generated by scripts/generate-seed-sql.mjs
-- user_id: b7fc22a7-de54-4621-b1df-cf526cf11d3c
begin;

-- 1) hs_events
insert into public.hs_events (user_id, title, slug, type, priority, status, start_date, end_date, description, source_doc, sort_order) values
  ('b7fc22a7-de54-4621-b1df-cf526cf11d3c', '世冠赛平台赛决赛美术提需', 'world-championship-platform-finals-design-request', 'milestone', 'critical', 'planned', '2025-04-01', '2025-04-01', '世冠赛平台赛决赛相关美术提需节点。', '网易大神炉石传说社区运营 - 2025年4月工作规划', 10),
  ('b7fc22a7-de54-4621-b1df-cf526cf11d3c', '冲钻领卡包活动上线', 'rank-push-card-pack-launch', 'campaign', 'critical', 'planned', '2025-04-03', '2025-04-03', '冲钻领卡包活动上线。', '网易大神炉石传说社区运营 - 2025年4月工作规划', 20),
  ('b7fc22a7-de54-4621-b1df-cf526cf11d3c', '世冠赛春季平台赛决赛', 'world-championship-spring-platform-finals', 'event', 'high', 'planned', '2025-04-10', '2025-04-12', '世冠赛春季平台赛决赛。', '网易大神炉石传说社区运营 - 2025年4月工作规划', 30),
  ('b7fc22a7-de54-4621-b1df-cf526cf11d3c', '黄金棋坛比赛', 'golden-battlegrounds-tournament', 'event', 'high', 'planned', '2025-04-18', '2025-04-19', '黄金棋坛比赛。', '网易大神炉石传说社区运营 - 2025年4月工作规划', 40);

-- 2) hs_tasks
insert into public.hs_tasks (user_id, event_id, title, task_type, priority, status, task_date, planned_date, due_date, source_type, notes)
select
  'b7fc22a7-de54-4621-b1df-cf526cf11d3c',
  e.id,
  v.title,
  v.task_type,
  v.priority,
  v.status,
  v.task_date,
  v.planned_date,
  v.due_date,
  v.source_type,
  v.notes
from (values
  ('world-championship-platform-finals-design-request', '提交世冠赛平台赛决赛美术提需', 'design', 'critical', 'pending', date '2025-04-01', date '2025-04-01', date '2025-04-01', 'imported', '根据 4 月工作规划执行。'),
  ('rank-push-card-pack-launch', '冲钻领卡包活动上线检查', 'launch', 'critical', 'pending', date '2025-04-03', date '2025-04-03', date '2025-04-03', 'imported', '上线前确认配置、展示与活动状态。'),
  ('world-championship-spring-platform-finals', '世冠赛春季平台赛决赛赛程配置', 'config', 'high', 'pending', date '2025-04-10', date '2025-04-08', date '2025-04-10', 'imported', '确保比赛前赛程配置完整。'),
  ('golden-battlegrounds-tournament', '黄金棋坛比赛执行跟进', 'ops', 'high', 'pending', date '2025-04-18', date '2025-04-17', date '2025-04-19', 'imported', '比赛期间执行与跟进。')
) as v(event_slug, title, task_type, priority, status, task_date, planned_date, due_date, source_type, notes)
left join public.hs_events e
  on e.slug = v.event_slug
 and e.user_id = 'b7fc22a7-de54-4621-b1df-cf526cf11d3c';

-- 3) hs_daily_checklists
insert into public.hs_daily_checklists (user_id, related_event_id, check_date, title, content, priority, status, source_type, sort_order)
select
  'b7fc22a7-de54-4621-b1df-cf526cf11d3c',
  e.id,
  v.check_date,
  v.title,
  v.content,
  v.priority,
  v.status,
  v.source_type,
  v.sort_order
from (values
  ('world-championship-platform-finals-design-request', date '2025-04-01', '世冠赛平台赛决赛美术提需', '处理世冠赛平台赛决赛相关美术提需。', 'critical', 'pending', 'imported', 10),
  ('rank-push-card-pack-launch', date '2025-04-03', '冲钻领卡包活动上线', '确认活动已按计划上线并检查关键配置。', 'critical', 'pending', 'imported', 20),
  ('world-championship-spring-platform-finals', date '2025-04-10', '世冠赛春季平台赛决赛 Day 1', '跟进世冠赛春季平台赛决赛首日执行事项。', 'high', 'pending', 'imported', 30),
  ('golden-battlegrounds-tournament', date '2025-04-18', '黄金棋坛比赛 Day 1', '跟进黄金棋坛比赛首日执行事项。', 'high', 'pending', 'imported', 40)
) as v(related_event_slug, check_date, title, content, priority, status, source_type, sort_order)
left join public.hs_events e
  on e.slug = v.related_event_slug
 and e.user_id = 'b7fc22a7-de54-4621-b1df-cf526cf11d3c';

commit;
